highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://jppmo.github.io/vitae
author: João Oliveira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: João Oliveira's Resume
name: João Oliveira
email: joaoliveira1990@gmail.com
email_full: mailto:joaoliveira1990@gmail.com
website: github.io/blog
website_full: https://jppmo.github.io/blog
github: trending
twitter: twitter
tel: 916796659
tel_full: tel:916796659
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
postcode:
city: Lisboa
country: Portugal
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
